<?php
namespace F3CMS;

/**
 * Filecache handler
 */
class FCHelper extends Reaction
{
    /**
     * @var int
     */
    public $ifHistory = 0;
    /**
     * @var string
     */
    private $base = 'cache';

    /**
     * constructor
     *
     * @param  object $dbInstance - db instance
     * @return none
     */
    public function __construct($action)
    {
        $this->base = f3()->get('abspath') . $this->base;

        if (!file_exists($this->base)) {
            mkdir($this->base, 0770, true);
        }

        $this->action = $action;
    }

    /**
     * @param  $filename
     * @param  $html
     * @return mixed
     */
    public function save($cacheName, $content)
    {
        $filename = $this->getFilename($cacheName);

        $content = self::minify($content) . PHP_EOL .
        '<!-- cache: ' . $cacheName . ' (generated at ' . date('y-m-d H:i:s') . ') DO NOT EDIT THIS FILE -->' . PHP_EOL . PHP_EOL;

        if ($this->ifHistory) {
            $bakname = $this->getBackupFilename();

            $this->writeFile($bakname, $content);

            $staff = f3()->get('SESSION.cs.name');

            $this->writeFile(
                $this->path . '/history.log',
                '|' . date('Y-m-d H:i:s') . PHP_EOL . '變動人：' . (($staff) ?: remote_ip()) . PHP_EOL . $bakname . PHP_EOL,
                'a+'
            );
        }

        $this->writeFile($filename, $content);

        return $content;
    }

    /**
     * @param $arg
     */
    public function do_get($f3, $args)
    {
        $req = parent::_getReq();
        extract($req, EXTR_SKIP);

        switch ($page) {
            case 'press':
                $this->action = 'press';
                break;
            default:
                $this->action = 'page';
                break;
        }

        $html = $this->get($this->action, 7200);

        return parent::_return(1, array('html' => $html));
    }

    /**
     * @param $cacheName
     * @param $useWildcard
     */
    public function flush($cacheName, $useWildcard)
    {
        if ($useWildcard) {
            $this->removeFiles('cache.' . $cacheName . '*.html');
        } else {
            $this->removeFiles('cache.' . $cacheName . '.html');
        }
    }

    public function flushAll()
    {
        $this->removeFiles('cache.*.html');
    }

    /**
     * @param  $cacheName
     * @param  $maxLifetime
     * @return mixed
     */
    public function get($cacheName, $maxLifetime = 0)
    {
        $filename = $this->getFilename($cacheName);

        if ($maxLifetime != 0 && $this->needRebuild($filename, $maxLifetime)) {
            return null;
            // return $this->requestSet($cacheName);
        }

        // load cache
        try {
            return $this->readCache($cacheName, $filename);
        } catch (\Exception $e) {
            return null;
        }
    }

    /**
     * @param $cacheName
     */
    public function getLog($cacheName)
    {
        $filename = $this->getFilename($cacheName);
        $content = @file_get_contents($this->base . $this->path . '/history.log');

        if ($content !== false) {
            $rtn = preg_split("/\|/u", $content);
            return array_filter(array_map('trim', $rtn));
        } else {
            return '';
        }
    }

    /**
     * @param $cacheName
     * @return mixed
     */
    public function requestSet($cacheName)
    {
        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL            => f3()->get('uri') . '/' . $this->action,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_ENCODING       => '',
            CURLOPT_MAXREDIRS      => 10,
            CURLOPT_TIMEOUT        => 30,
            CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST  => 'GET',
            CURLOPT_HTTPHEADER     => array(
                'cache-control: no-cache'
            )
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
            return 'cURL Error #:' . $err;
        } else {
            return $this->set($this->action, $response, 60);
        }
    }

    /**
     * @param $path
     * @param $content
     * @param $mode
     */
    private function writeFile($path, $content, $mode = 'w+')
    {
        if (!file_exists($this->base . $path)) {
            touch($this->base . $path);
        }

        $handler = fopen($this->base . $path, $mode);
        fwrite($handler, $content);
        fclose($handler);
    }

    /**
     * Returns cache filename.
     *
     * @param  string   $cacheName
     * @return string
     */
    protected function getFilename($cacheName)
    {
        $this->path = '/' . $this->action . '/' . md5($cacheName);

        if (!file_exists($this->base . $this->path)) {
            mkdir($this->base . $this->path, 0770, true);
        }

        return $this->path . '/index.html';
    }

    /**
     * Returns cache filename.
     *
     * @return string
     */
    protected function getBackupFilename()
    {
        return $this->path . '/' . date('ymdHis') . '.html';
    }

    /**
     * Removes files matching given pattern.
     *
     * @param string $pattern
     */
    protected function removeFiles($pattern)
    {
        $directory = $this->base . '/' . $this->action . '/';

        foreach (glob($directory . $pattern) as $filename) {
            @unlink($filename);
        }
    }

    /**
     * Determines wheater the cache needs to be rebuild or not.
     *
     * @param  string    $filename
     * @param  integer   $maxLifetime
     * @return boolean
     */
    protected function needRebuild($filename, $maxLifetime)
    {
        // cache does not exist
        if (!file_exists($this->base . $filename)) {
            return true;
        }

        // cache is empty
        if (!@filesize($this->base . $filename)) {
            return true;
        }

        // cache resource was marked as obsolete
        if (($mtime = filemtime($this->base . $filename)) <= 1) {
            return true;
        }

        // maxlifetime expired
        if ($maxLifetime > 0 && (time() - $mtime) > $maxLifetime * 60) {
            return true;
        }

        // do not rebuild cache
        return false;
    }

    /**
     * Loads the file of a cached resource.
     *
     * @param  string  $cacheName
     * @param  string  $filename
     * @return mixed
     */
    protected function readCache($cacheName, $filename)
    {
        if (!file_exists($this->base . $filename)) {
            return '';
        }

        // get file contents
        $content = file_get_contents($this->base . $filename);

        // find first newline
        $position = strpos($content, PHP_EOL);
        if ($position === false) {
            throw new \Exception('Unable to load cache resource "' . $cacheName . '"');
        }

        // cut contents
        $contents = substr($contents, $position + 1);

        return $content;
    }

    /**
     * Loads the file of a cached resource.
     *
     * @param  string  $filename
     * @return mixed
     */
    public function readHistory($filename)
    {
        // get file contents
        $content = file_get_contents($this->base . $filename);

        // find first newline
        $position = strpos($content, PHP_EOL);
        if ($position === false) {
            throw new \Exception('Unable to load cache resource "' . $filename . '"');
        }

        return $content;
    }

    /**
     * @param  $buffer
     * @return mixed
     */
    public static function minify($buffer)
    {
        //return $buffer;

        $search = array(
            '/\>[^\S ]+/s', // strip whitespaces after tags, except space
            '/[^\S ]+\</s', // strip whitespaces before tags, except space
            '/(\s)+/s' // shorten multiple whitespace sequences
        );

        $replace = array(
            '>',
            '<',
            '\\1'
        );

        $buffer = preg_replace($search, $replace, $buffer);

        return $buffer;
    }
}
