<?php

namespace F3CMS;

/**
 * static file render handler
 */
class SRHelper extends Helper
{
    const NOT_LOG_HISTORY = false;

    /**
     * @param $filename
     * @param $html
     *
     * @return mixed
     */
    public static function save($staticPath, $content, $follow = true)
    {
        $filename = self::getFilename($staticPath);

        $content = self::minify($content) . PHP_EOL .
        '<!-- cache: ' . $staticPath . ' (generated at ' . date('y-m-d H:i:s') . ') DO NOT EDIT THIS FILE -->' . PHP_EOL . PHP_EOL;

        if ($follow) {
            $bakname = self::getBackupFilename($staticPath);

            FSHelper::dumpFile(f3()->get('UPLOAD_PATH') . $bakname, $content);

            $staff = rStaff::_CStaff('name');

            FSHelper::appendToFile(
                f3()->get('UPLOAD_PATH') . $staticPath . '/history.log',
                '|' . date('Y-m-d H:i:s') . PHP_EOL . '變動人：' . (($staff) ?: f3()->IP) . PHP_EOL . $bakname . PHP_EOL
            );
        }

        FSHelper::dumpFile(f3()->get('UPLOAD_PATH') . $filename, $content);

        return $content;
    }

    /**
     * @param $staticPath
     * @param $useWildcard
     */
    public static function flush($staticPath, $useWildcard)
    {
        if ($useWildcard) {
            self::removeFiles('cache.' . $staticPath . '*.html');
        } else {
            self::removeFiles('cache.' . $staticPath . '.html');
        }
    }

    public static function flushAll()
    {
        self::removeFiles('cache.*.html');
    }

    /**
     * @param $staticPath
     * @param $maxLifetime
     *
     * @return mixed
     */
    public static function get($staticPath, $maxLifetime = 0)
    {
        $filename = self::getFilename($staticPath);

        if (0 != $maxLifetime && self::needRebuild($filename, $maxLifetime)) {
            return null;
            // return self::requestSet($staticPath);
        }

        // load cache
        try {
            return self::readCache($staticPath, $filename);
        } catch (\Exception $e) {
            return null;
        }
    }

    public static function getLog($staticPath)
    {
        $filename = self::getFilename($staticPath);
        $content  = @file_get_contents(f3()->get('UPLOAD_PATH') . self::path . '/history.log');

        if (false !== $content) {
            $rtn = preg_split("/\|/u", $content);

            return array_filter(array_map('trim', $rtn));
        } else {
            return '';
        }
    }

    public static function requestSet($staticPath)
    {
        $curl = curl_init();

        curl_setopt_array($curl, [
            CURLOPT_URL            => f3()->get('uri') . '/' . self::action,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_ENCODING       => '',
            CURLOPT_MAXREDIRS      => 10,
            CURLOPT_TIMEOUT        => 30,
            CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST  => 'GET',
            CURLOPT_HTTPHEADER     => [
                'cache-control: no-cache',
            ],
        ]);

        $response = curl_exec($curl);
        $err      = curl_error($curl);

        curl_close($curl);

        if ($err) {
            return 'cURL Error #:' . $err;
        } else {
            return self::set(self::action, $response, 60);
        }
    }

    /**
     * Returns cache filename.
     *
     * @param string $staticPath
     *
     * @return string
     */
    protected static function getFilename($staticPath)
    {
        FSHelper::mkdir(f3()->get('UPLOAD_PATH') . $staticPath);

        return $staticPath . '/index.html';
    }

    /**
     * Returns cache filename.
     *
     * @return string
     */
    protected static function getBackupFilename($staticPath)
    {
        return $staticPath . '/' . date('ymdHis') . '.html';
    }

    /**
     * Removes index matching given path.
     *
     * @param string $path
     */
    protected static function removeFiles($path)
    {
        // TODO: lang ary
        $files = FSHelper::ls(f3()->get('UPLOAD_PATH') . $path);
        foreach ($files as $file) {
            if ('index.html' == basename($file)) {
                if (file_exists($file)) {
                    unlink($file);
                }
            }
        }
    }

    /**
     * Determines wheater the cache needs to be rebuild or not.
     *
     * @param string $filename
     * @param int    $maxLifetime
     *
     * @return bool
     */
    protected static function needRebuild($filename, $maxLifetime)
    {
        // cache does not exist
        if (!file_exists(f3()->get('UPLOAD_PATH') . $filename)) {
            return true;
        }

        // cache is empty
        if (!@filesize(f3()->get('UPLOAD_PATH') . $filename)) {
            return true;
        }

        // cache resource was marked as obsolete
        if (($mtime = filemtime(f3()->get('UPLOAD_PATH') . $filename)) <= 1) {
            return true;
        }

        // maxlifetime expired
        if ($maxLifetime > 0 && (time() - $mtime) > $maxLifetime * 60) {
            return true;
        }

        // do not rebuild cache
        return false;
    }

    /**
     * Loads the file of a cached resource.
     *
     * @param string $staticPath
     * @param string $filename
     *
     * @return mixed
     */
    protected static function readCache($staticPath, $filename)
    {
        if (!file_exists(f3()->get('UPLOAD_PATH') . $filename)) {
            return '';
        }

        // get file contents
        $content = FSHelper::openFile(f3()->get('UPLOAD_PATH') . $filename);

        // find first newline
        $position = strpos($content, PHP_EOL);
        if (false === $position) {
            throw new \Exception('Unable to load cache resource "' . $staticPath . '"');
        }

        // cut contents
        $contents = substr($contents, $position + 1);

        return $content;
    }

    /**
     * Loads the file of a cached resource.
     *
     * @param string $filename
     *
     * @return mixed
     */
    public static function readHistory($filename)
    {
        // get file contents
        $content = file_get_contents(f3()->get('UPLOAD_PATH') . $filename);

        // find first newline
        $position = strpos($content, PHP_EOL);
        if (false === $position) {
            throw new \Exception('Unable to load cache resource "' . $filename . '"');
        }

        return $content;
    }

    /**
     * @param $buffer
     *
     * @return mixed
     */
    public static function minify($buffer)
    {
        // return $buffer;

        $search = [
            '/\>[^\S ]+/s', // strip whitespaces after tags, except space
            '/[^\S ]+\</s', // strip whitespaces before tags, except space
            '/(\s)+/s', // shorten multiple whitespace sequences
        ];

        $replace = [
            '>',
            '<',
            '\\1',
        ];

        $buffer = preg_replace($search, $replace, $buffer);

        return $buffer;
    }
}
